// ---------------- coaster layout (control points, metres) ----------------
// Vertical loop generated by integrating curvature so that the felt G-force follows a smooth
// profile (≈3.6 G at the bottom, ≈1.2 G at the top) -> physically correct "clothoid" teardrop loop.
function genLoop(S, dir, lat, y0, v0sq, width) {
  const g = 9.81, out = [];
  let th = 0, x = 0, y = 0, acc = 0, sTot = 0;
  const ds = 0.05, half = [[0, 0, 0]];
  // integrate the rising half (tangent angle 0 -> PI), then mirror it about the apex: symmetric loop
  while (th < Math.PI) {
    const v2 = Math.max(v0sq - 2 * g * y * 1.04, 20);
    let Gt = 1.2 + 2.4 * Math.pow(Math.cos(th / 2), 2);
    Gt = 1 + (Gt - 1) * Math.max(0.06, Math.min(1, sTot / 9)); // clothoid easement: G ramps in over 9 m
    sTot += ds;
    const kap = (g * Gt - g * Math.cos(th)) / v2; // felt G along inward normal = (v^2 k + g n_y)/g
    th += kap * ds; x += Math.cos(th) * ds; y += Math.sin(th) * ds; acc += ds;
    if (acc >= 2.2) { acc = 0; half.push([x, y, th]); }
  }
  const xt = x, yt = y;
  if (acc < 1.1) half[half.length - 1] = [xt, yt, Math.PI]; else half.push([xt, yt, Math.PI]);
  for (let i = half.length - 2; i >= 0; i--) half.push([2 * xt - half[i][0], half[i][1], 2 * Math.PI - half[i][2]]);
  out.push(...half);
  return out.map(([x, y, t]) => {
    const f = t / (Math.PI * 2), sh = width * (f * f * (3 - 2 * f));
    return [S[0] + dir[0] * x + lat[0] * sh, y0 + y, S[2] + dir[2] * x + lat[2] * sh];
  });
}
function coasterControlPoints() {
  const pts = [
    [-34, 2.5, 22], [-18, 2.5, 22], [-4, 2.5, 22], [6, 2.5, 22],           // station
    [13, 4, 22], [21, 12, 22], [30, 24, 22], [38, 34, 22], [44, 38.5, 22], [49, 39.2, 22], // chain lift + crest
    [55, 35.5, 22], [60, 28, 22], [65, 18.5, 22], [70, 11.5, 22], [76, 7, 22], [83, 4.8, 22], [92, 4.2, 21.7], // first drop with long pull-out
    [101, 5, 19], [110, 7, 11], [114, 9.5, -1], [111, 10.5, -13], [102, 9, -22], [90, 6, -26], [78, 4, -26], // banked, rising U-turn with easements
  ];
  const loop = genLoop([64, 0, -26], [-1, 0, 0], [0, 0, -1], 3.6, 2 * 9.81 * (39.2 - 3.6) * 0.80, 7);
  pts.push(...loop);
  pts.push([14, 4.8, -33.2],
    // zig-zag S-curves with gentle air-time hills (half-wavelength 26 m, amplitude ±4.5 m)
    [-4, 9, -37.5], [-28, 6, -29], [-54, 9, -38], [-76, 6, -30],
    // final turn back to the brake run
    [-90, 5.5, -21], [-97, 5, -7], [-94, 4, 8], [-83, 3, 18], [-66, 2.5, 22], [-50, 2.5, 22]);
  return pts;
}
function coasterMarks(pts) {
  return { launch: [[-34, 2.5, 22], [12, 3.6, 22]], lift: [[12, 3.6, 22], [48, 39.2, 22]], brake: [pts[pts.length - 2], [-14, 2.5, 22]], stop: [-1, 2.5, 22] };
}
if (typeof module !== 'undefined') module.exports = { coasterControlPoints, coasterMarks, genLoop };
